version: '3.8'
name: weahter-app-graphql
services:
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.3-alpine3.18